services:
  nest-app:
    build:
      context: yu-gi-oh-api
      dockerfile: api.Dockerfile
    container_name: nest-docker-app
    ports:
      - '3000:3000'
    volumes:
      - ./yu-gi-oh-api/src:/app/src
  angular-client:
    build:
      context: yu-gi-oh-client
      dockerfile: client.Dockerfile
    container_name: angular-docker-client
    ports:
      - '4200:4200'
    volumes:
      - ./yu-gi-oh-client/src:/app/src
  db:
    image: postgres 
    restart: always 
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    depends_on: 
      - nest-app
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'


